### ISSUE TITLE
Invalid decoder for `Map` (dictionary) field

### ISSUE THREAD

**Issue by ehamberg** [krisajenkins/elm-export#37]
Given the Haskell data type

```
data Foo = Foo { foo :: Map String Int }
```

An example response from Aeson (via Servant) is

```
{
    "foo": {
        "1": 1,
        "2": 2
    }
}
```

However, the decoder for `Foo` generated by `elm-export` is the following:

```
decodeFoo : Decoder Foo
decodeFoo =
    decode Foo
        |> required "foo" (map Dict.fromList (list (map2 (,) (index 0 string) (index 1 int))))
```

i.e. it's expecting a list, not an object. This mismatch can be verified by actually attempting to decode data from Elm:

    "Expecting a List at _.foo but instead got: {\"1\":1,\"2\":2}"

I have created a repository with a self-contained program that can be used to reproduce the issue here: https://github.com/ehamberg/elm-export-test

I have tested this on version 0.6.0.1 and `devel@ 7ca89b88393925ebd27ace8c919cec1fe0f511c0`.

**Comment by tekul** [comment]
@ehamberg  Any chance you could submit your fix for the string key case as a PR? it seems to be the correct behaviour.

I was looking into this a bit more and aeson seems to stick with a simple key/value encoding for  maps with simple types such as String or Int, so these will all fail with the current implementation as far as I an see, e.g.

```haskell
> let x=M.fromList [(1, "1"), (2, "2"), (3, "3)] :: M.Map Int String
> Data.Aeson.encode x
"{\"1\":\"1\",\"2\":\"2\",\"3\":\"3\"}"
```
But for more complex cases, such as tuple keys, it switches to using lists:

```haskell
>  x = M.fromList [((1,1),"1"),((2,2),"2"),((3,3),"3")]
> > Data.Aeson.encode x
"[[[1,1],\"1\"],[[2,2],\"2\"],[[3,3],\"3\"]]"
```
I'd expect the primitive (particularly string) key cases will be the most common, so it would be nice to have a fix in place.

**Comment by ehamberg** [comment]
Yep. Will do that next week.
